# Generic circle.yml for using the Terminus Build Tools Plugin to
# test a Pantheon site. See the README for customization instructions.

machine:
  timezone:
    America/Chicago
  php:
    # https://circleci.com/docs/build-image-trusty/#php
    version: 7.0.11
  environment:
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/1.0/environment-variables/
    #
    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
    # TERMINUS_TOKEN: The Pantheon machine token
    # GITHUB_TOKEN:   The GitHub personal access token
    # GIT_EMAIL:      The email address to use when making commits
    #
    # TEST_SITE_NAME: The name of the test site to provide when installing.
    # ADMIN_PASSWORD: The admin password to use when installing.
    # ADMIN_EMAIL:    The email address to give the admin when installing.
    #
    # The variables below usually do not need to be modified.
    BRANCH: $(echo $CIRCLE_BRANCH | grep -v '^\(master\|[0-9]\+.x\)$')
    PR_ENV: ${BRANCH:+pr-$BRANCH}
    CIRCLE_ENV: ci-$CIRCLE_BUILD_NUM
    DEFAULT_ENV: $(echo ${PR_ENV:-$CIRCLE_ENV} | tr '[:upper:]' '[:lower:]' | sed 's/[^0-9a-z-]//g' | cut -c -11 | sed 's/-$//')
    TERMINUS_ENV: ${TERMINUS_ENV:-$DEFAULT_ENV}
    NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
    PATH: $PATH:~/bin:tests/scripts

dependencies:
  cache_directories:
    - ~/.composer/cache
  pre:
    - echo "Begin test"
 
  override:
    - composer global require -n "hirak/prestissimo:^0.3"
    - /usr/bin/env COMPOSER_BIN_DIR=$HOME/bin composer --working-dir=$HOME require "pantheon-systems/terminus:^1"
    - terminus --version
    - mkdir -p ~/.terminus/plugins
    - composer create-project -n -d ~/.terminus/plugins fusionx1/terminus-get-newrelic
   
  post:
    - terminus auth:login -n --machine-token="$TERMINUS_TOKEN"

test:
  override:
    - composer test
